### ISSUE TITLE
Error while calling a function to fetch data

### ISSUE THREAD

**Issue by Tamxaun** [AlecAivazis/houdini#66] opened 2021-04-21 09:44 UTC
I have a error when trying fetching data with basic code from example:

_index.svelte_
```
<script lang="ts">
	import { query, graphql, AllProducts } from '$houdini';

	// load the items
	const { data } = query<AllProducts>(graphql`
		query AllProducts {
			allProducts {
				name
			}
		}
	`);
</script>
```

Message error:
```
Error: Function called outside component initialization
    at get_current_component (/home/domitori/project/node_modules/svelte/internal/index.js:652:18)
    at Object.setContext (/home/domitori/project/node_modules/svelte/internal/index.js:682:25)
    at Object.setVariables (/home/domitori/project/src/node_modules/$houdini/runtime/context.js:5:63)
    at Object.query (/home/domitori/project/src/node_modules/$houdini/runtime/query.js:19:26)
    at /home/domitori/project/src/routes/index.svelte:34:32
    at Object.$$render (/home/domitori/project/node_modules/svelte/internal/index.mjs:1366:23)
    at Object.default (/home/domitori/project/src/node_modules/@sapper/internal/App.svelte:20:50)
    at /home/domitori/project/__sapper__/dev/server/server.js:4174:38
    at Object.$$render (/home/domitori/project/node_modules/svelte/internal/index.mjs:1366:23)
    at /home/domitori/project/src/node_modules/@sapper/internal/App.svelte:16:18
```

I use template _tonyketcham/sapper-tailwind2-template_ as local

Graphql server from local keystone

**Comment by AlecAivazis** [comment] 2021-04-24 00:02
Hey @Tamxaun - thanks for opening this issue. Let's see if we can figure out what's going on.

Just to double check, i copied the example directory from this repo to a fresh location and ran `yarn && yarn dev` and everything worked as expected. Do you mind pushing up your code somewhere I can pull and give it a look?

**Comment by Tamxaun** [comment] 2021-04-24 23:18
to simplicity for my case you could clone tonyketcham/sapper-tailwind2-template and after install houdini how you suggesting in readme

1. yarn add -D houdini houdini-preprocess
2. run npx houdini init
3. add 
2. change index.svelte to 
```svelte
<svelte:head>
  <title>Sapper project template</title>
</svelte:head>

<section class="flex flex-col space-y-3">
  <div class="relative flex justify-center">
    <h1 class="relative flex m-6 text-5xl">3</h1>
  </div>
</section>

<script lang="ts">
  import { query, graphql, AllItems } from '$houdini';

  // load the items
  const { data } = query<AllItems>(graphql`
    query AllItems {
      items {
        id
        text
        completed
      }
    }
  `);
</script>
```

1.

**Comment by Tamxaun** [comment] 2021-04-24 23:36
for simplicity of my case you can clone this template [tonyketcham/sapper-tailwind2-template](https://github.com/tonyketcham/sapper-tailwind2-template) and afterwards install houdini as you suggest in the readme:

1. clone template
```
npx degit "tonyketcham/sapper-tailwind2-template" my-winded-app
cd my-winded-app
yarn install
yarn dev
```
2. install houdini `yarn add -D houdini houdini-preprocess`
3. `run npx houdini init`
4. add preprocessor to rollup config
```
import houdini from 'houdini-preprocess'

// somewhere in your config file
{
    plugins: [
        svelte({
            preprocess: [houdini()],
        }),
    ]
}
```
5. add client and server environments
 ```
// in both src/client.js and src/server.js

import { setEnvironment } from '$houdini'
import env from './environment'

setEnvironment(env)
```
6. Change `index.svelte` to 
```svelte
<svelte:head>
  <title>Sapper project template</title>
</svelte:head>

<section class="flex flex-col space-y-3">
  {#each $data.items as item}
    <div class="relative flex justify-center">{item.text}</div>
  {/each}
</section>

<script lang="ts">
  import { query, graphql, AllItems } from '$houdini';

  // load the items
  const { data } = query<AllItems>(graphql`
    query AllItems {
      items {
        id
        text
        completed
      }
    }
  `);
</script>
```
7. run `npx houdini generate`
8. run `yarn dev`

**Comment by AlecAivazis** [comment] 2021-04-25 00:57
Good to hear the default example is working - i also appreciate the detailed instructions. Unfortunately, I do not have a huge amount of free time atm (hence why the kit stuff isn't in yet) so I would appreciate if you could follow those steps and push it up somewhere so I can try to take a look between other responsibilities

**Comment by Tamxaun** [comment] 2021-04-25 15:31
https://github.com/Tamxaun/my-winded-app

**Comment by AlecAivazis** [comment] 2021-04-25 18:04
@Tamxaun - i pulled down your repo but I dont see an API here to run. Am i missing something?

**Comment by Tamxaun** [comment] 2021-04-25 20:20
ok, I added api

**Comment by AlecAivazis** [comment] 2021-04-27 23:05
Thanks for pushing that up. I pulled down your project and reproduced the error. After poking around in the generated code, I noticed that the issue goes away if I remove the invocations of `onMount`, `onDestroy` and `setContext` from the generated body of `query`. I think this points to a configuration problem since source online say that this can be caused by listed `svelte` as a `dependency` instead of a `devDependency`. 

I dont have a solution for you just yet, but I just wanted to share my findings in case you have any ideas of what could be different between your project and the demo that's causing this.

**Comment by Tamxaun** [comment] 2021-04-29 22:06
thanks, I check for every dependency and found that if install latest version of _@rollup/plugin-node-resolve_ and _@rollup/plugin-commonjs_ that error will appear.

**Comment by AlecAivazis** [comment] 2021-05-15 23:04
Some good new @Tamxaun - I just successfully ran the sapper example from the `kit` with the latest version of all of the dependencies. Do you mind pulling that down and seeing if you can go through the steps you outlined above on that branch?

**Comment by AlecAivazis** [comment] 2021-05-18 05:53
Going to close this issue as I've built up a working sapper project with the latest dependencies a number of times from the `@kit` branch. Feel free to open another if you are still running into problem @Tamxaun

**Closed by AlecAivazis** 2021-05-18 05:53 UTC
