### ISSUE TITLE
Unterminated Regular Expression error on Generate

### ISSUE THREAD

**Issue by thormuller** [AlecAivazis/houdini#108] opened 2021-06-30 00:51 UTC
When I run `npx houdini generate` I'm now getting an error as follows:

```
SyntaxError: Unterminated regular expression (32:3)
    at Object._raise (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:1871:17)
    at Object.raiseWithData (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:1864:17)
    at Object.raise (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:1832:17)
    at Object.readRegexp (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:9880:20)
    at Object.readToken_slash (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:9492:12)
    at Object.getTokenFromCode (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:9808:14)
    at Object.getTokenFromCode (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:8646:20)
    at Object.nextToken (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:9331:12)
    at Object.parse (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:14929:10)
    at parse$1$1 (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:14984:38) {
  loc: Position$1 { line: 32, column: 3 },
  pos: 822
```
Running latest `0.8.0`. Does this error map to any known issues?

**Comment by AlecAivazis** [comment] 2021-06-30 05:30
Hm, it _could_ be related to the new parser but the error message should be different if that was the case. Did you change any files between version bumps? I suspect the easiest way to debug this will be to push up the repo somewhere i can pull down.

**Comment by AlecAivazis** [comment] 2021-06-30 05:59
Ah actually I see you commenting that you have seen this work since `0.7.2` which is when the parser was introduced. The update in `0.8.0` should only affect you if you were using `mode: svelte` in your config which I don't think you were... 🤔

**Comment by AlecAivazis** [comment] 2021-06-30 06:44
version `0.8.1` should provide you a slightly more helpful error message

**Comment by AlecAivazis** [comment] 2021-06-30 16:05
@thormuller i just opened #110 which replaces the custom parser for the one from svelte. This _should_ fix your problem (if it was in fact caused by the parser)

**Comment by thormuller** [comment] 2021-06-30 21:18
Brilliant. Worked like a charm for generating the runtime files. 

Not sure if this is related, but the `generate` script ends with the following error:

```
RangeError: Maximum call stack size exceeded
    at OrType.check (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:54570:39)
    at addParam (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:54924:27)
    at <APPLICATION_PATH>/node_modules/houdini/build/cmd.js:54956:21
    at Array.forEach (<anonymous>)
    at Object.builder [as identifier] (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:54954:46)
    at <APPLICATION_PATH>/node_modules/houdini/build/cmd.js:75059:48
    at Array.map (<anonymous>)
    at inputType (<APPLICATION_PATH>/node_modules/houdini/build/cmd.js:75058:78)
    at <APPLICATION_PATH>/node_modules/houdini/build/cmd.js:75061:34
    at Array.map (<anonymous>)
```

**Comment by AlecAivazis** [comment] 2021-06-30 21:42
I don't think its related, I suspect the problem is because you have a recursive input type. Does that sound familiar?

**Comment by thormuller** [comment] 2021-06-30 22:09
Thanks for that tip. I'll have to ferret it out.

**Comment by AlecAivazis** [comment] 2021-06-30 22:10
I'm going to close this issue - I opened #111 to track that as it does in fact blow things up with the same error

**Closed by AlecAivazis** 2021-06-30 22:10 UTC
Labels: Awaiting Confirmation

**Comment by AlecAivazis** [comment] 2021-06-30 23:53
@thormuller - `0.8.3` fixed the issue with recursive input types. Mind seeing if your issue is still a thing?
