### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by SorenHolstHansen** [AlecAivazis/houdini#137] opened 2021-07-17 14:40 UTC
I see that houdini requires node version 15 or higher to work, however hosting providers like vercel only go as high as node version 14.x. Is there a reason for needing 15 or higher, otherwise it would be great to allow for lower versions

**Comment by AlecAivazis** [comment] 2021-07-17 17:02
This `engines` field was set in order to avoid an `Unexpected token *` exception that was reported in #103. It's caused by an `import * from ...` statement in the built version of the cli. To be honest, I didn't really investigate if there were versions less than `15.0.0` that supported this syntax but it's definitely important to be able to support vercel. If you have the time to find a version that works, I'd really appreciate it. Otherwise I can investigate it a bit more once I'm done with pagination.

**Comment by SorenHolstHansen** [comment] 2021-07-17 20:17
I can maybe make the time tomorrow, will see

**Comment by SorenHolstHansen** [comment] 2021-07-17 23:52
How do I reproduce the issue in #103, am unsure if the issue is not reintroduced when I change stuff.

**Comment by AlecAivazis** [comment] 2021-07-20 06:01
I think the only way to reproduce it is to downgrade your node version (with something like `nvm`) to find the lowest version that houdini supports. If I remember correctly, the error would happen when invoking the `init` function but it's probably safest to also make sure that the `generate` command also works in a given version. You can use the example app if you need something to test against. If the minimal version isn't supported by vercel, we'll have to figure out how to tweak the build configuration to compile the sourcecode into something that can run on their environment.

**Comment by AlecAivazis** [comment] 2021-07-20 16:41
Closing this since #139 has been merged. Thanks again @SorenHolstHansen

**Closed by AlecAivazis** 2021-07-20 16:41 UTC
